### ISSUE TITLE
compile error on mac os

### ISSUE THREAD

**Issue by bwanaaa** [IAIK/meltdown#15]
MacBook Pro (Retina, 15-inch, Late 2013)
El-Capitan
```

%make
make -C libkdump
gcc -c -fPIC libkdump.c -o libkdump.o -O3 -pthread -Wno-attributes
libkdump.c:349:5: warning: expression result unused [-Wunused-value]
    nopthread;
    ^~~~~~~~~
1 warning generated.
ar rcs libkdump.a libkdump.o
gcc -shared -Wl,-soname,libkdump.so -o libkdump.so libkdump.o -O3 -pthread -Wno-attributes
clang: warning: argument unused during compilation: '-pthread'
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libkdump.so] Error 1
make: *** [libkdump/libkdump.a] Error 2
```

```
%make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
%
```

**Comment by carlorosati** [comment]
https://stackoverflow.com/questions/4580789/ld-unknown-option-soname-on-os-x

**Comment by aryeh-looker** [comment]
If you remove that compilation option (which I'm not sure is even legit); i.e.:

```
$ git diff
diff --git a/libkdump/Makefile b/libkdump/Makefile
index ea400b8..73df424 100644
--- a/libkdump/Makefile
+++ b/libkdump/Makefile
@@ -7,7 +7,7 @@ libkdump.o: libkdump.c
        $(CC) -c -fPIC libkdump.c -o libkdump.o $(CFLAGS)
        
 libkdump.so: libkdump.o
-       $(CC) -shared -Wl,-soname,libkdump.so -o libkdump.so libkdump.o $(CFLAGS)
+       $(CC) -shared -Wl,libkdump.so -o libkdump.so libkdump.o $(CFLAGS)
        
 libkdump.a: libkdump.o
        ar rcs libkdump.a libkdump.o 
```

... there are still some issues:

```
$ make
gcc kaslr.c -o kaslr -Llibkdump -Ilibkdump -lkdump -static -O3 -pthread -Wno-attributes 
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [kaslr] Error 1
```

**Comment by bogem** [comment]
I'm just trying to build it as in it's written in README and become same issue as @aryeh-looker:
```
gcc kaslr.c -o kaslr -Llibkdump -Ilibkdump -lkdump -static -O3 -pthread -Wno-attributes 
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [kaslr] Error 1
```
iMac 2012, macOS High Sierra 10.13.2.

**Comment by johnlinvc** [comment]
Looks like `crt0.o` is not available on macOS
we need to build it our self
https://github.com/skaht/Csu-85

**Comment by neglectedvalue** [comment]
Do executables have to be compiled statically at all?

I have got them compiled without `-static` with `libkdump.a`.
Nonetheless, demos highly dependant on Linux-specifics (`taskset`, `KASLR`, and `/proc/<pid>/pagemap`) and aren't working out on Mac OS.

Looking forward to someone who gets it working on Mac!

**Comment by misc0110** [comment]
As none of us has a  Mac, we cannot look into this issue.

**Comment by lapcat** [comment]
I just put the source files into an Xcode project and build there instead of using the makefiles. That works fine.

(I haven't yet been able to read kernel memory on a Mac, however. It seems the race condition is getting lost.)

**Comment by misc0110** [comment]
I don't know whether Mac has the same direct physical map as Linux (and whether it is at the same location), so the examples might not work without adaption on Mac. 

Furthermore, Mac is already patched, so even if you have the correct offset, you might already have the patches applied.

**Comment by stankusl** [comment]
On mac libraries are dynamic and you cannot use --static on your c compiler.

**Comment by lapcat** [comment]
> I don't know whether Mac has the same direct physical map as Linux (and whether it is at the same location), so the examples might not work without adaption on Mac.

It's not the same as Linux, so the address does have to be customized for the Mac.

**Comment by tlam9631** [comment]
Testing on Linux > Kali > VirtualBox > Mac OS > Mac Book, with i386 should be a valid test environment, if Mac Book is the choice of hardware.

**Comment by herbierobinson** [comment]
You may find you need to do even more tweaking to get this to work on a non-Linux OS.  I've been having difficulty.  Haven't totally figured out what's going on, yet, but I suspect that a particularly ponderous SIGSEGV implementation is flushing too much stuff and losing too much state from the previous iteration.  

One thing I can tell you to watch out for is the loop embedded in the assembly language sequences called "meltdown" and "meltdown_nonull":  This can result in an infinite loop if the byte you are trying to read is really zero and the probing behavior becomes completely stable (like if you are testing libkdump by reading data you actually have read access to).  The "meltdown_test" test case only reads ASCII data; so, you can get zinged by thinking you fully tested the "access to data I can read case".

**Comment by misc0110** [comment]
The infinite loop is only a problem if you read data which is accessible. In any other case, it will at some point abort due to the exception.

**Comment by herbierobinson** [comment]
Correct.  Thanks for clarifying my rather cryptic prose :-).
