### ISSUE TITLE
Compile error on 32 bit Ubuntu 16.04

### ISSUE THREAD

**Issue by howardzhang87** [IAIK/meltdown#17]
Hi, I'm using Ubuntu 16.04 32bit VM. I got the following error when building libkdump:
![image](https://user-images.githubusercontent.com/27936526/34768367-a44b447e-f5c8-11e7-840f-12e215968670.png)
`Linux version 4.10.0-42-generic (buildd@lgw01-amd64-051) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017`
`Linux VM 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 i686 i686 i686 GNU/Linux`

**Comment by howardzhang87** [comment]
@misc0110 Your recent update solves the above compile error. But I got a new error:
![image](https://user-images.githubusercontent.com/27936526/34776678-a9ec6ada-f5e5-11e7-9c48-ec3c3ef8e374.png)
Maybe it's here?
![image](https://user-images.githubusercontent.com/27936526/34776766-e7d07e36-f5e5-11e7-9374-7973708e1818.png)

**Comment by misc0110** [comment]
Do you have the newest commit? Looks like you are on an old commit.

**Comment by howardzhang87** [comment]
@misc0110 Yes, it's the newest. It's exactly the same the code as in the current repository.

**Comment by misc0110** [comment]
But your error message does not match the code. It says "bad register name %rax" in line 485 of libkdump.c, but in this line there is only a variable declaration: https://github.com/IAIK/meltdown/blob/master/libkdump/libkdump.c#L485

Have you tried `make clean` before building it again?

**Comment by howardzhang87** [comment]
@misc0110 Yes, I did clean before I `make`. And I just deleted the local repository and re-git clone. Same error. Confused.

**Comment by howardzhang87** [comment]
@misc0110 I just changed those rax, rbx, rcx I mentioned above to eax, ebx and ecx respectively, and everything works fine now. I don't understand why compiler generated the wrong error message pointing to a different line.

**Comment by paboldin** [comment]
@howardzhang87 GCC line numbers are broken for inline assembly, because it believes all the code to be in a single line.
