### ISSUE TITLE
Demo #2: Breaking KASLR (kaslr) doesn't stop

### ISSUE THREAD

**Issue by BAM0S** [IAIK/meltdown#19]
I disabled the KASLR on my Ubuntu.
Demo number 1 worked well.
I ran demo number 2 but it doesn't stop and already 5 **minutes** passed and I don't think it going to stop.
![image](https://user-images.githubusercontent.com/35255728/34773872-e0e589ba-f615-11e7-907b-2ea1fadf586d.png)

Any idea what can be the reason ?

I am using the last update #14.

**Comment by misc0110** [comment]
The demo starts with quite large steps to iterate over the address space. If it wraps around, it reduces the step size. So it might take quite long, depending on how much entropy your operating system uses. Have you tried restarting it?

**Comment by BAM0S** [comment]
I have 2910~
```
myUser@ubuntu:~/Desktop/meltdown$ cat /proc/sys/kernel/random/entropy_avail
2923

```

By the way, on one execution it found it after couple of seconds.
I tried again, and again it takes time.

I restart the machine, now the entropy was 903 but when I run `sudo taskset 0x1 ./kaslr` again it takes more than 1 minute and still searching..

**Comment by FalkF** [comment]
Isn't KASLR supposed to be on, if you try "Breaking KASLR" ?

**Comment by misc0110** [comment]
We will soon add another tool to simply read out the KASLR offset from the kernel (if the KASLR tool does not work).

**Comment by sanderjo** [comment]
FWIW: 

On my system (Intel Celeron N2840, Ubuntu 17.10 with Linux 4.13.0-041300-generic), demo works, but kaslr does not result in anything after one hour of searching.

![meltdown results](https://user-images.githubusercontent.com/1273502/34794154-0ba2cb30-f64e-11e7-8f01-c563e0324a44.png)

```
$ cat /proc/sys/kernel/random/entropy_avail
3523
```

**Comment by misc0110** [comment]
If the kaslr program does not work, I've added a kernel module to the repository that reads the offset directly from the kernel (in folder `kaslr_offset`). Just run `sudo ./direct_physical_map.sh`. It requires the Linux kernel headers of the current kernel to be installed to build the kernel module. You can get them with ```sudo apt-get install linux-headers-`uname -r` ``` (on Ubuntu).

**Comment by sanderjo** [comment]
```
sander@Stream-13:~/git/meltdown/kaslr_offset$ sudo ./direct_physical_map.sh
[+] Building kernel module
make -C /lib/modules/4.13.0-041300-generic/build M=/home/sander/git/meltdown/kaslr_offset/kernel_module modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-041300-generic'
  CC [M]  /home/sander/git/meltdown/kaslr_offset/kernel_module/direct_physical_map.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/sander/git/meltdown/kaslr_offset/kernel_module/direct_physical_map.mod.o
  LD [M]  /home/sander/git/meltdown/kaslr_offset/kernel_module/direct_physical_map.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-041300-generic'
[+] Loading kernel module
[+] Direct physical map offset at 0xffff8d9000000000
```
second run:
```
sander@Stream-13:~/git/meltdown/kaslr_offset$ sudo ./direct_physical_map.sh
[+] Direct physical map offset at 0xffff8d9000000000
```
... that is fast!

**Comment by misc0110** [comment]
@sanderjo Because it does not use Meltdown, but reads it directly from the kernel ;)

**Comment by BAM0S** [comment]
Works, it found the address.
![image](https://user-images.githubusercontent.com/35255728/34817233-18c95a00-f6c0-11e7-82ed-d86b6c4d6814.png)

I suggest to add it to the readme file.

**Comment by Pavitra7** [comment]
When i run the ./direct_physical_map.sh, i get the following error
![Screenshot from 2021-09-22 23-28-27](https://user-images.githubusercontent.com/58722233/134396914-9206d47a-ee0f-49bc-9e1b-3097d05a4028.png)
r.

Please help me resolve the issue
