### ISSUE TITLE
Why reliability test has only 0.40% ?

### ISSUE THREAD

**Issue by BAM0S** [IAIK/meltdown#20]
I followed your instructions.
I ran the `./test` and it works fine.
I ran the `./kaslr` and it found me the offset.

I took the offset and ran it with the `./reliability` file but it is only 0.39%.

![image](https://user-images.githubusercontent.com/35255728/34776744-85c60392-f620-11e7-930f-85f8e78f6361.png)

Can you explain why ?

**Comment by misc0110** [comment]
Meltdown is a race condition where a lot of things influence how well it works. We observe the same on our machines - on some it works really well (nearly 100% reliability), on others it is similar to your result. 
On some machines it helps to run the stress tool in the background to get a higher reliability.

**Comment by rohan-0100010110010100** [comment]
@misc0110 thanks for explanation had  similar issue , banging my head for 4 straight hours to figure out the results.

**Comment by BAM0S** [comment]
After I used `./direct_physical_map.sh`:
`~/Desktop/meltdown/kaslr_offset$ sudo ./direct_physical_map.sh`

It found me the address and when I checked the reliability I received 100%.

Thanks.
