### ISSUE TITLE
Cannot reproduce on i5-6300hq?

### ISSUE THREAD

**Issue by dascandy** [IAIK/meltdown#25]
Running kernel from 18-12-2017, 4.13.0. The test program runs reliably (tried 50x), the kaslr determination finds its address, reliability run as root finds 100.0% success (rounded up), but physical_reader with identical arguments does not return at all. Is there something I can try or adjust to see why not?

System was last rebooted 5 days ago, so should not have any microcode patches either.

**Comment by dgruss** [comment]
On 11.01.2018 09:36, Peter Bindels wrote:
> Running kernel from 18-12-2017, 4.13.0. The test program runs reliably (tried 50x), the kaslr determination finds its
> address, reliability run as root finds 100.0% success (rounded up), but physical_reader with identical arguments does
> not return at all. Is there something I can try or adjust to see why not?

Can you try pinning it to different core combinations with taskset?
Maybe on your system the race condition is too tight for the Meltdown implementation we use in libkdump...

**Comment by dascandy** [comment]
Tried running 4 at a time, one pinned to each core, while leaving the secret program pinned to core 0x8. The ones on 0x1, 0x2, 0x4 don't return anything, and the one pinned on core 0x8 returns what issue #3 returns as well.

**Comment by dgruss** [comment]
On 11.01.2018 10:43, Peter Bindels wrote:
> Tried running 4 at a time, one pinned to each core, while leaving the secret program pinned to core 0x8. The ones on
> 0x1, 0x2, 0x4 don't return anything, and the one pinned on core 0x8 returns what issue #3
> <https://github.com/IAIK/meltdown/issues/3> returns as well.

Then the implementation simply does not win the race condition on your system in cross-core and uncached scenarios.
You would have to use a more optimized implementation to win the race, which we do not publish at this point.

**Comment by dascandy** [comment]
Can I in some way assist in trying to make a branchless / cmov variant of meltdown?

**Comment by dgruss** [comment]
Our plan is to not publish our optimizations within the next weeks.

**Comment by misc0110** [comment]
You can try the things I added to the FAQ section in the readme.
