### ISSUE TITLE
Breaking KASLR and Reliability test does not work on Ubuntu 16.04 32bit

### ISSUE THREAD

**Issue by howardzhang87** [IAIK/meltdown#27]
I'm running a Ubuntu 16.04 32 bit VM with KASLR disabled. When I run Breaking KASLR demo, I got this:
![image](https://user-images.githubusercontent.com/27936526/34869957-9ff04584-f756-11e7-96a8-813cbffebde4.png)
And the reliability demo runs extremely slow with success rate 0.00%. These two demos work smoothly on my 64 bit VM.

**Comment by misc0110** [comment]
The `kaslr` demo only works on 64-bit systems right now due to a hardcoded offset of the direct physical map. Will update soon.

**Comment by misc0110** [comment]
Fixed in 064a2fa3f7c59e4ca275d1a7c0d6a5b9f73c7390
