### ISSUE TITLE
Can't see the secret from demo #4 (physical_reader)

### ISSUE THREAD

**Issue by BAM0S** [IAIK/meltdown#3]
I followed the instructions.

First, I disabled the KASL with ([reference](https://askubuntu.com/questions/318315/how-can-i-temporarily-disable-aslr-address-space-layout-randomization)):
`echo 0 | sudo tee /proc/sys/kernel/randomize_va_space`

I ran `sudo ./secret` and it succeeded.

But when I tried to read the memory from the physical address, everything was not readable:
![image](https://user-images.githubusercontent.com/35255728/34732840-1862cbfc-f56f-11e7-98f9-5f442b40f66a.png)

Any idea why ? 
  

**EDIT:** 
I tried also after reboot and verified that the KASL is disabled.
For this I created the file: `/etc/sysctl.d/01-disable-aslr.conf`
with the content: `kernel.randomize_va_space = 0`

**Comment by dgruss** [comment]
Try our kaslr tool first, it will detect the kaslr offset.

**Comment by pRiVi** [comment]
If I run the secret with taskset

`taskset 0x1 ./physical_reader 0x714fe54a8 0xffff8db1c0000000`

I see the same error as BAM0S does do.

**Comment by misc0110** [comment]
Does this always happen?
A few things you can try:

- Try different combinations of taskset (e.g. both on the same core, different cores)
- Fix your CPU frequency to maximum
- Start the tool stress (apt-get install stress) with -i 1 or -i 2, or if this does not work stress -i 1 -m 1 -c 1 to generate more load

**Comment by pRiVi** [comment]
See #9

**Comment by BAM0S** [comment]
@misc0110 I tried the options you mentioned with the **stress** tool but it is still printing unreadable content.

**Comment by tlam9631** [comment]
Amy update on "@misc0110 I tried the options you mentioned with the stress tool but it is still printing unreadable content." ? I tried with and with KASR disabled with the same unreable content as BAMOS did. Thanks.

Or anyone ever got demo 4 and 5 working who can share exact settings? Thanks.

**Comment by dgruss** [comment]
The settings and even implementation details will vary from system to 
system. I have one system where prefetching helps for instance, whereas 
it seems to reduce the performance significantly.
Nothing complex, an attacker could just try a set of a few different 
approaches and pick the one that works best. But this is not the goal of 
our PoCs.

**Comment by pRiVi** [comment]
@dgruss Yes, your goal is only to make your paper look as big as possible.

**Comment by misc0110** [comment]
You can try the things I added to the FAQ section in the readme.
