### ISSUE TITLE
meltdown without sudo

### ISSUE THREAD

**Issue by walkerlala** [IAIK/meltdown#30]
The README says that 

> This demo requires root privileges to speed up the process. The paper describes a variant which does not require root privileges

However the paper does not seem to contain any material on that (probably in references **[6, 9, 13, 17]**. Haven't checked those papers yet). Can anyone point me to the section which contains those material?

**Comment by misc0110** [comment]
It is outlined in section 5.2 (Dealing with KASLR). And as you mentioned, references [9, 13, 17] also describe how to do that.
