### ISSUE TITLE
Build error on Debian Wheezy

### ISSUE THREAD

**Issue by crist0phe** [IAIK/meltdown#47]
This is my output:

$ make
make -C libkdump
make[1]: entrant dans le répertoire « /home/christophe/meltdown-master/libkdump »
gcc -c -fPIC libkdump.c -o libkdump.o -O3 -pthread -Wno-attributes
libkdump.c: In function 'libkdump_read_tsx':
libkdump.c:485:7: error: inconsistent operand constraints in an 'asm'
make[1]: *** [libkdump.o] Erreur 1
make[1]: quittant le répertoire « /home/christophe/meltdown-master/libkdump »
make: *** [libkdump/libkdump.a] Erreur 2

$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i486-linux-gnu/4.7/lto-wrapper
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by misc0110** [comment]
Can you try if it works for you with the changes from pull request "Force 64bit mode #26"?

**Comment by crist0phe** [comment]
Hi misc0110,
With these modifications, compilation is OK. But it generates a 64 bits output and I must test on a 32 bits system, so the test does not work.

**Comment by dgruss** [comment]
won't fix
