### ISSUE TITLE
Cannot read secret value

### ISSUE THREAD

**Issue by 723novy723** [IAIK/meltdown#50]
Hi, I was able to proceed through first three steps. I got almost the same results, like reliability of reading was about 99% etc. The bad thing now is the step 4 (Demo #4). I have two terminals, first has started the secret program (./secret) and in the second console is started the physical reader (taskset 0x1 ./physical_reader ...). I am not getting any secret words nor printable chars. I just see the chars that are repeatedly printed in the terminal. See the attached screen. Can anybody help me how to get it? I have unpatched Ubuntu version 14.04.05 64bit. It should definitly work.
![capture](https://user-images.githubusercontent.com/37138738/37082717-8e445b9c-21ed-11e8-9bec-27e8de853786.PNG)

**Comment by dgruss** [comment]
the code is optimized for same-core attacks. try other values for taskset so that the two programs run on the same core.

**Comment by 723novy723** [comment]
Do you mean this? **taskset 0x2** ./reliability 0xffff880000000000
I am beginner at Linux. Thx

**Comment by dgruss** [comment]
For instance, yes. Or taskset 0x4, etc. Just check the documentation for taskset.

**Comment by 723novy723** [comment]
By the way, I am running the Ubuntu on Virtual Box configured as one CPU. Let me play with your ideas...

**Comment by dgruss** [comment]
Not sure that this is going to work at all.

The code is not optimized for running in virtual machines.

**Comment by 723novy723** [comment]
I see, Would it help to run it on Linux live version? I do not want to install Linux parallel with Win on drive.

**Comment by dgruss** [comment]
Yes

**Comment by 723novy723** [comment]
Hey, I was able to reproduce it on Ubuntu Live. Thanks for hint!!!
