### ISSUE TITLE
It doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by lemorn** [IAIK/meltdown#61]
Hello! I tried have tried these demos but the demo-4 can't work. It didn't ouput anything. And the reliability test showed that success rate is 0%. My ubuntu is 18.04.1. Is it because this version of ubuntu has patched this vulnerability？

**Comment by misc0110** [comment]
If you didn't change any boot parameters, KPTI is enabled by default, mitigating Meltdown.
