### ISSUE TITLE
Flags for compile time configuration

### ISSUE THREAD

**Issue by beef9** [IAIK/meltdown#63]
The flag "MELTDOWN: The variant of Meltdown to use" does not work when written in the Makefile file. Example:
(Makefile): 

>  override CFLAGS += -O3 -pthread -Wno-attributes -m64 -USE_RDTSCP -MELTDOWN 

Outputs the following error:

>gcc test.c -o test -m64 -Llibkdump -Ilibkdump -lkdump -static -O3 -pthread -Wno-attributes -m64 -USE_RDTSCP -MELTDOWN
gcc: error: unrecognized command line option ‘-MELTDOWN’
Makefile:15: recipe for target 'test' failed
make: *** [test] Error 1

Also, it does not seem to work with the following flags:
-meltdown_nonull, --meltdown_nonull, -METLDOWN=meltdown_nonull, --METLDOWN.

**Comment by misc0110** [comment]
These configs are not compiler options, but C defines. Hence, you have to provide them using the -D option of your compiler, e.g.,

    override CFLAGS += -O3 -pthread -Wno-attributes -m64 -DUSE_RDTSCP -DMELTDOWN=meltdown_nonull

**Comment by beef9** [comment]
Thanks for clarifying, I got confused because the "-USE_RDTSCP" flag worked for me without errors.

**Comment by misc0110** [comment]
That is because -U is a valid option. It *undefines* a macro, in your case you would undefine the definition of `SE_RDTSCP` (which is likely not defined anyways).

**Comment by beef9** [comment]
I understand now. This issue can be closed.
