### ISSUE TITLE
What's the meaning of the line 382 and 383 in libkdump/libkdump.c?

### ISSUE THREAD

**Issue by ghost** [IAIK/meltdown#64]
Hi,
    I use the _mem instead of mem as the base address, and use 4096*256 rather than 4096*290, it also works in some . I have a question why you do that?

Thanks!

**Comment by misc0110** [comment]
4096 * 256 should also work. We just added a few extra pages to reduce the chances of any noise, e.g., from the prefetcher, but this should not be necessary. _mem and mem both refer to the same memory range, but mem is aligned to a page boundary. _mem is probably also page-aligned in most cases, but this is not guaranteed.
